{{- $svc := default (dict) .Values.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frostgate-core.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "frostgate-core.name" . }}
    helm.sh/chart: {{ include "frostgate-core.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ default "ClusterIP" (get $svc "type") | quote }}
  ports:
    - name: http
      port: {{ default 80 (get $svc "port") }}
      targetPort: {{ default 8080 (get $svc "targetPort") }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "frostgate-core.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}