from __future__ import annotations

from enum import StrEnum


class TriageCategory(StrEnum):
    CONTRACT_DRIFT = "CONTRACT_DRIFT"
    DUPLICATE_ROUTES = "DUPLICATE_ROUTES"
    PLANE_REGISTRY_DRIFT = "PLANE_REGISTRY_DRIFT"
    AUTH_SCOPE_MISMATCH = "AUTH_SCOPE_MISMATCH"
    TENANT_ISOLATION_BREACH = "TENANT_ISOLATION_BREACH"
    RLS_MISSING_OR_WEAK = "RLS_MISSING_OR_WEAK"
    SSRF_GUARD_FAILURE = "SSRF_GUARD_FAILURE"
    MIGRATION_RISK = "MIGRATION_RISK"
    TIME_BUDGET_EXCEEDED = "TIME_BUDGET_EXCEEDED"
    FLAKE_SUSPECTED = "FLAKE_SUSPECTED"
    UNKNOWN = "UNKNOWN"
