name: "fg-python-setup"
description: "Install OS deps, setup Python with cache, create workspace, build venv"
inputs:
  python-version:
    description: "Python version"
    required: false
    default: "3.12"
  install-os-deps:
    description: "Whether to install OS deps"
    required: false
    default: "true"
  prepare-workspace:
    description: "Whether to create state/artifacts dirs"
    required: false
    default: "true"
  build-venv:
    description: "Whether to run make venv"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install OS deps (retrying)
      if: ${{ inputs.install-os-deps == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update || (sleep 5 && sudo apt-get update)
        sudo apt-get install -y sqlite3 curl zip minisign ripgrep

    - name: Set up Python (cached)
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: |
          pyproject.toml
          requirements.txt
          requirements-dev.txt
          requirements-test.txt
          uv.lock
          poetry.lock

    - name: Prepare workspace
      if: ${{ inputs.prepare-workspace == 'true' }}
      shell: bash
      run: |
        mkdir -p state artifacts keys

    - name: Build venv + deps
      if: ${{ inputs.build-venv == 'true' }}
      shell: bash
      run: |
        make venv
