# policy/bundles/nginx.conf
pid /tmp/nginx.pid;

events {}

http {
  client_body_temp_path /tmp/client_body_temp;
  proxy_temp_path       /tmp/proxy_temp;
  fastcgi_temp_path     /tmp/fastcgi_temp;
  uwsgi_temp_path       /tmp/uwsgi_temp;
  scgi_temp_path        /tmp/scgi_temp;

  server {
    listen 80;

    location /health { return 200 "ok\n"; }

    location / {
      root /usr/share/nginx/html;
      try_files $uri =404;
    }
  }
}