import { NavigationRegistry } from '../registry';
import type { NavigationItem } from '../types';

export const CONSOLE_REGISTRY = new NavigationRegistry();

const items: NavigationItem[] = [
  // ─── Operations ──────────────────────────────────────────────────────────────

  {
    id: 'executive-intelligence',
    title: 'Executive Intelligence',
    route: '/dashboard/executive',
    group: 'Operations',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Executive', 'CISO', 'Auditor', 'Administrator'],
    aliases: [
      'executive center', 'strategic intelligence', 'board view', 'exec dashboard',
      'ceo dashboard', 'ciso command', 'governance command', 'executive workspace',
    ],
    keywords: [
      'executive', 'board', 'strategic', 'governance health', 'compliance score',
      'risk heatmap', 'forecast', 'recommendations', 'business impact', 'audit readiness',
    ],
    metadata: {
      mcimId: 'MCIM-18.6.7-EXEC-INTEL',
      capability: 'Executive Intelligence Center',
      family: 'intelligence',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/executive/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Primary executive workspace for CEOs, CIOs, CISOs, Boards, and regulators — deterministic governance intelligence derived from accumulated evidence, with board-ready reporting and evidence-backed forecasts.',
    },
  },

  {
    id: 'command-center',
    title: 'Command Center',
    route: '/dashboard',
    group: 'Operations',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Operator', 'Administrator', 'CISO', 'Executive'],
    aliases: ['dashboard', 'home', 'overview', 'main', 'ops hub'],
    keywords: ['real-time', 'status', 'metrics', 'kpi', 'summary', 'posture'],
    metadata: {
      mcimId: 'MCIM-18.6-CMD-CENTER',
      capability: 'Operational Command Center',
      family: 'operator-execution',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Single-pane-of-glass for real-time AI governance posture, active alert triage, and executive KPI visibility.',
    },
  },

  {
    id: 'control-tower',
    title: 'Control Tower',
    route: '/dashboard/control-tower',
    group: 'Operations',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Operator', 'Administrator', 'Support'],
    aliases: ['control plane', 'gateway', 'traffic', 'requests', 'monitor'],
    keywords: ['gateway', 'traffic', 'latency', 'request volume', 'policy enforcement', 'runtime'],
    metadata: {
      mcimId: 'MCIM-18.6-CTRL-TOWER',
      capability: 'Runtime Control Tower',
      family: 'operator-execution',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/control-tower/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Live visibility into AI gateway traffic, per-model request rates, and policy enforcement outcomes at runtime.',
    },
  },

  // ─── Governance ──────────────────────────────────────────────────────────────

  {
    id: 'readiness',
    title: 'Readiness',
    route: '/dashboard/readiness',
    group: 'Governance',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Operator', 'CISO', 'Auditor', 'Executive'],
    aliases: ['ai readiness', 'risk score', 'posture', 'compliance score', 'maturity'],
    keywords: ['readiness', 'score', 'maturity', 'risk', 'gap', 'framework', 'assessment'],
    metadata: {
      mcimId: 'MCIM-18.6-READINESS',
      capability: 'AI Readiness Assessment',
      family: 'continuous-posture',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/readiness/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Continuous posture scoring against NIST AI RMF, ISO 42001, and custom frameworks — quantifies governance maturity for executives and auditors.',
    },
  },

  {
    id: 'field-assessments',
    title: 'Field Assessments',
    route: '/field-assessment',
    group: 'Governance',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Operator', 'AssessmentEngineer', 'FieldAssessor', 'Administrator'],
    aliases: [
      'engagements',
      'assessments list',
      'field ops',
      'site assessment',
      'on-site',
      'field work',
    ],
    keywords: ['field', 'engagement', 'assessment', 'on-site', 'client', 'survey'],
    metadata: {
      mcimId: 'MCIM-18.6-FIELD-ASSESS',
      capability: 'Field Assessment Management',
      family: 'delivery',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/field-assessment/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Centralised view of all active and completed field engagement sessions, enabling operators to dispatch assessors and track completion.',
    },
  },

  {
    id: 'policies',
    title: 'Policies',
    route: '/dashboard/policies',
    group: 'Governance',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Operator', 'Compliance', 'CISO'],
    aliases: ['policy editor', 'rules', 'opa', 'guardrails', 'policy management'],
    keywords: ['policy', 'rule', 'opa', 'guardrail', 'enforcement', 'allow', 'deny', 'condition'],
    metadata: {
      mcimId: 'MCIM-18.6-POLICIES',
      capability: 'AI Policy Authoring',
      family: 'trust-policy',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/policies/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Enables compliance and CISO teams to author, version, and deploy OPA-based AI use policies without engineering support.',
    },
  },

  {
    id: 'providers',
    title: 'Providers',
    route: '/dashboard/providers',
    group: 'Governance',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Operator', 'Administrator', 'CISO'],
    aliases: ['ai providers', 'models', 'llm config', 'anthropic', 'openai', 'model registry'],
    keywords: ['provider', 'model', 'llm', 'api key', 'endpoint', 'configuration', 'vendor'],
    metadata: {
      mcimId: 'MCIM-18.6-PROVIDERS',
      capability: 'AI Provider Configuration',
      family: 'platform-admin',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/providers/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Single registry for all upstream AI model providers — controls which models are permitted, rate-limited, and policy-checked.',
    },
  },

  {
    id: 'field-assessment-detail',
    title: 'Field Assessment Detail',
    route: '/field-assessment/[engagementId]',
    group: 'Governance',
    tier: 'contextual',
    classification: 'contextual',
    visibility: 'hidden',
    platform: 'console',
    roles: ['Operator', 'AssessmentEngineer', 'FieldAssessor', 'Administrator'],
    aliases: ['engagement detail', 'field session', 'assessment view'],
    keywords: ['engagement', 'field', 'detail', 'session', 'assessment', 'site'],
    breadcrumbParent: 'field-assessments',
    metadata: {
      mcimId: 'MCIM-18.6-FIELD-DETAIL',
      capability: 'Field Assessment Detail',
      family: 'delivery',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/field-assessment/[engagementId]/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Deep-dive view of a single field engagement — question responses, scoring progress, and assessor notes.',
    },
  },

  {
    id: 'governance-topology',
    title: 'Governance Topology',
    route: '/governance/topology',
    group: 'Governance',
    tier: 'specialist',
    classification: 'specialist',
    visibility: 'conditional',
    platform: 'console',
    roles: ['Operator', 'CISO', 'Administrator'],
    aliases: ['topology', 'graph', 'dependency map', 'governance map', 'policy graph'],
    keywords: ['topology', 'graph', 'dependency', 'map', 'structure', 'hierarchy', 'governance'],
    metadata: {
      mcimId: 'MCIM-18.6-GOV-TOPOLOGY',
      capability: 'Governance Topology Visualisation',
      family: 'ai-governance',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/governance/topology/page.tsx',
      maturity: 'partial',
      lifecycle: 'growing',
      businessValue:
        'Visual graph of policy inheritance, provider relationships, and control ownership — exposes structural gaps before they become audit findings.',
    },
  },

  // ─── Intelligence ─────────────────────────────────────────────────────────────

  {
    id: 'ai-workspace',
    title: 'AI Workspace',
    route: '/dashboard/assistant',
    group: 'Intelligence',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Operator', 'Developer'],
    aliases: ['assistant', 'ai chat', 'chat', 'llm', 'ask ai', 'operator chat'],
    keywords: ['assistant', 'chat', 'ai', 'llm', 'prompt', 'query', 'conversation', 'rag'],
    metadata: {
      mcimId: 'MCIM-18.6-AI-WORKSPACE',
      capability: 'Operator AI Workspace',
      family: 'knowledge',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/assistant/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Governed AI chat environment for operators — every query runs through the policy engine and is logged to the audit chain.',
    },
  },

  {
    id: 'corpus',
    title: 'Corpus',
    route: '/dashboard/corpus',
    group: 'Intelligence',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Operator', 'Developer', 'Administrator'],
    aliases: ['knowledge base', 'documents', 'embeddings', 'corpus management', 'knowledge corpus'],
    keywords: [
      'corpus',
      'document',
      'embedding',
      'knowledge',
      'upload',
      'index',
      'vector',
      'chunk',
    ],
    metadata: {
      mcimId: 'MCIM-18.6-CORPUS',
      capability: 'Knowledge Corpus Management',
      family: 'knowledge',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/corpus/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Manages the curated knowledge corpus powering RAG — controls what the AI system knows and can cite.',
    },
  },

  {
    id: 'retrieval',
    title: 'Retrieval',
    route: '/dashboard/retrieval',
    group: 'Intelligence',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Operator', 'Developer'],
    aliases: ['rag', 'retrieval config', 'search config', 'vector search', 'retrieval tuning'],
    keywords: ['retrieval', 'rag', 'search', 'vector', 'similarity', 'rerank', 'pipeline'],
    metadata: {
      mcimId: 'MCIM-18.6-RETRIEVAL',
      capability: 'Retrieval Pipeline Configuration',
      family: 'knowledge',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/retrieval/page.tsx',
      maturity: 'functional',
      lifecycle: 'stable',
      businessValue:
        'Tunes retrieval parameters — embedding models, similarity thresholds, re-ranking — to maximise answer quality from the corpus.',
    },
  },

  {
    id: 'workforce-intel',
    title: 'Workforce Intel',
    route: '/dashboard/workforce',
    group: 'Intelligence',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Operator', 'CISO', 'Executive'],
    aliases: ['workforce', 'staff analytics', 'user analytics', 'people analytics', 'hr insights'],
    keywords: ['workforce', 'employees', 'usage', 'adoption', 'risk', 'behaviour', 'analytics'],
    metadata: {
      mcimId: 'MCIM-18.6-WORKFORCE',
      capability: 'Workforce Intelligence Analytics',
      family: 'intelligence',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/workforce/page.tsx',
      maturity: 'functional',
      lifecycle: 'growing',
      businessValue:
        'Identifies AI usage patterns, shadow-AI risk, and training gaps across the workforce — feeds HR and CISO risk reporting.',
    },
  },

  {
    id: 'ingestion',
    title: 'Ingestion',
    route: '/dashboard/ingestion',
    group: 'Intelligence',
    tier: 'specialist',
    classification: 'specialist',
    visibility: 'conditional',
    platform: 'console',
    roles: ['Operator', 'Developer'],
    aliases: ['data ingestion', 'pipeline', 'connectors', 'feed', 'ingest'],
    keywords: ['ingestion', 'pipeline', 'connector', 'feed', 'import', 'data', 'source'],
    metadata: {
      mcimId: 'MCIM-18.6-INGESTION',
      capability: 'Data Ingestion Pipeline',
      family: 'knowledge',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/ingestion/page.tsx',
      maturity: 'partial',
      lifecycle: 'growing',
      businessValue:
        'Manages structured and unstructured data feeds into the corpus — enables automated, policy-compliant knowledge updates.',
    },
  },

  // ─── Trust ───────────────────────────────────────────────────────────────────

  {
    id: 'provenance',
    title: 'Provenance',
    route: '/dashboard/provenance',
    group: 'Trust',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Auditor', 'CISO', 'Operator'],
    aliases: ['data lineage', 'lineage', 'source tracing', 'ai provenance', 'chain of custody'],
    keywords: ['provenance', 'lineage', 'source', 'trace', 'origin', 'chain', 'custody'],
    metadata: {
      mcimId: 'MCIM-18.6-PROVENANCE',
      capability: 'AI Provenance Tracing',
      family: 'trust-explainability',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/provenance/page.tsx',
      maturity: 'functional',
      lifecycle: 'stable',
      businessValue:
        'Traces every AI output back to its source documents and policy decisions — critical for regulated industry explainability requirements.',
    },
  },

  {
    id: 'decisions',
    title: 'Decisions',
    route: '/dashboard/decisions',
    group: 'Trust',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Auditor', 'CISO', 'Executive', 'Operator'],
    aliases: ['decision log', 'decision history', 'ai decisions', 'policy decisions', 'rulings'],
    keywords: ['decision', 'log', 'allow', 'deny', 'policy', 'outcome', 'ruling', 'history'],
    metadata: {
      mcimId: 'MCIM-18.6-DECISIONS',
      capability: 'AI Decision Ledger',
      family: 'trust-audit',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/decisions/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Immutable ledger of every policy decision made by the AI gateway — provides defensible audit trail for regulators.',
    },
  },

  {
    id: 'forensics',
    title: 'Audit & Forensics',
    route: '/dashboard/forensics',
    group: 'Trust',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Auditor', 'Support'],
    aliases: ['audit', 'forensics', 'audit log', 'hmac audit', 'tamper-evident', 'event log'],
    keywords: ['audit', 'forensics', 'hmac', 'tamper', 'log', 'event', 'chain', 'integrity'],
    metadata: {
      mcimId: 'MCIM-18.6-FORENSICS',
      capability: 'Forensic Audit Chain',
      family: 'trust-forensics',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/forensics/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'HMAC-chained audit log that proves no event has been tampered with — satisfies regulator requests for forensic evidence.',
    },
  },

  {
    id: 'alignment',
    title: 'Alignment',
    route: '/dashboard/alignment',
    group: 'Trust',
    tier: 'specialist',
    classification: 'specialist',
    visibility: 'conditional',
    platform: 'console',
    roles: ['CISO', 'Executive'],
    aliases: ['ai alignment', 'framework alignment', 'control alignment', 'nist alignment'],
    keywords: ['alignment', 'framework', 'nist', 'iso', 'control', 'mapping', 'coverage'],
    metadata: {
      mcimId: 'MCIM-18.6-ALIGNMENT',
      capability: 'Framework Alignment Mapping',
      family: 'trust-center',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/alignment/page.tsx',
      maturity: 'partial',
      lifecycle: 'growing',
      businessValue:
        'Maps deployed controls to NIST AI RMF, ISO 42001, and SOC 2 requirements — generates gap analysis for CISO and executive reporting.',
    },
  },

  {
    id: 'audit-specialist',
    title: 'Audit',
    route: '/audit',
    group: 'Compliance',
    tier: 'specialist',
    classification: 'specialist',
    visibility: 'conditional',
    platform: 'console',
    roles: ['Auditor', 'Support'],
    aliases: ['deep audit', 'full audit', 'audit workspace', 'auditor view'],
    keywords: ['audit', 'review', 'specialist', 'deep', 'workspace', 'compliance'],
    metadata: {
      mcimId: 'MCIM-18.6-AUDIT-SPEC',
      capability: 'Specialist Audit Workspace',
      family: 'trust-forensics',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/audit/page.tsx',
      maturity: 'functional',
      lifecycle: 'stable',
      businessValue:
        'Specialist workspace for auditors requiring deeper event inspection and cross-tenant evidence compilation beyond the standard forensics view.',
    },
  },

  // ─── Compliance ───────────────────────────────────────────────────────────────

  {
    id: 'evaluation-lab',
    title: 'Evaluation Lab',
    route: '/dashboard/evaluation',
    group: 'Compliance',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Developer', 'Administrator', 'Operator'],
    aliases: ['eval', 'evaluation', 'model eval', 'benchmarks', 'testing', 'quality'],
    keywords: ['evaluation', 'benchmark', 'quality', 'test', 'model', 'metric', 'accuracy'],
    metadata: {
      mcimId: 'MCIM-18.6-EVAL-LAB',
      capability: 'AI Evaluation Laboratory',
      family: 'ai-quality',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/evaluation/page.tsx',
      maturity: 'functional',
      lifecycle: 'stable',
      businessValue:
        'Structured environment for running model quality benchmarks and generating compliance evidence for regulated AI system validation.',
    },
  },

  // ─── Administration ────────────────────────────────────────────────────────────

  {
    id: 'clients',
    title: 'Clients',
    route: '/admin/tenants',
    group: 'Administration',
    tier: 'administrative',
    classification: 'administrative',
    visibility: 'visible',
    platform: 'console',
    roles: ['Administrator', 'Support'],
    aliases: ['tenants', 'tenant management', 'clients', 'organizations', 'orgs', 'accounts'],
    keywords: ['tenant', 'client', 'organisation', 'account', 'multi-tenant', 'manage'],
    metadata: {
      mcimId: 'MCIM-18.6-CLIENTS',
      capability: 'Client Tenant Management',
      family: 'platform-admin',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/admin/tenants/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Master list of all provisioned client tenants — administrators create, configure, and suspend tenants from this surface.',
    },
  },

  {
    id: 'client-detail',
    title: 'Client Detail',
    route: '/admin/tenants/[tenantId]',
    group: 'Administration',
    tier: 'contextual',
    classification: 'contextual',
    visibility: 'hidden',
    platform: 'console',
    roles: ['Administrator', 'Support'],
    aliases: ['tenant detail', 'tenant view', 'client view', 'client profile'],
    keywords: ['tenant', 'client', 'detail', 'profile', 'configuration', 'settings'],
    breadcrumbParent: 'clients',
    metadata: {
      mcimId: 'MCIM-18.6-CLIENT-DETAIL',
      capability: 'Client Tenant Detail',
      family: 'platform-admin',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/admin/tenants/[tenantId]/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Per-tenant configuration surface — feature flags, billing tier, user roster, and integration settings.',
    },
  },

  {
    id: 'keys',
    title: 'Keys',
    route: '/keys',
    group: 'Administration',
    tier: 'administrative',
    classification: 'administrative',
    visibility: 'visible',
    platform: 'console',
    roles: ['Administrator', 'Operator'],
    aliases: ['api keys', 'key management', 'tokens', 'credentials', 'access keys'],
    keywords: ['key', 'api', 'token', 'credential', 'secret', 'access', 'rotate'],
    metadata: {
      mcimId: 'MCIM-18.6-KEYS',
      capability: 'API Key Lifecycle Management',
      family: 'identity-grants',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/keys/page.tsx',
      maturity: 'functional',
      lifecycle: 'stable',
      businessValue:
        'Self-service API key issuance, rotation, and revocation — reduces credential sprawl and supports least-privilege access.',
    },
  },

  {
    id: 'settings',
    title: 'Settings',
    route: '/dashboard/settings',
    group: 'Administration',
    tier: 'administrative',
    classification: 'administrative',
    visibility: 'visible',
    platform: 'console',
    roles: ['Operator', 'Administrator'],
    aliases: ['platform settings', 'config', 'preferences', 'system settings'],
    keywords: ['settings', 'configuration', 'preferences', 'system', 'platform', 'setup'],
    metadata: {
      mcimId: 'MCIM-18.6-SETTINGS',
      capability: 'Platform Settings',
      family: 'platform-admin',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/dashboard/settings/page.tsx',
      maturity: 'functional',
      lifecycle: 'stable',
      businessValue:
        'Centralised platform configuration — notification preferences, integration toggles, and display settings for operators and administrators.',
    },
  },

  // ─── Hidden / Non-Nav Pages ──────────────────────────────────────────────────

  {
    id: 'console-landing',
    title: 'Landing',
    route: '/',
    group: 'Operations',
    tier: 'hidden',
    classification: 'hidden',
    visibility: 'hidden',
    platform: 'console',
    roles: ['Operator', 'Administrator', 'CISO', 'Executive', 'Auditor', 'Developer', 'Support'],
    aliases: ['root', 'home', 'index'],
    keywords: ['landing', 'root', 'home'],
    metadata: {
      mcimId: 'MCIM-18.6-LANDING',
      capability: 'Console Entry Point',
      family: 'platform-ops',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue: 'Entry point that redirects authenticated users to Command Center.',
    },
  },

  {
    id: 'console-login',
    title: 'Login',
    route: '/login',
    group: 'Administration',
    tier: 'hidden',
    classification: 'hidden',
    visibility: 'hidden',
    platform: 'console',
    roles: ['Operator', 'Administrator', 'CISO', 'Executive', 'Auditor', 'Developer', 'Support'],
    aliases: ['sign in', 'auth', 'authenticate'],
    keywords: ['login', 'sign in', 'auth', 'authentication'],
    metadata: {
      mcimId: 'MCIM-18.6-CON-LOGIN',
      capability: 'Console Authentication',
      family: 'identity-grants',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/login/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue: 'Secure authentication gate for all console users.',
    },
  },

  {
    id: 'onboarding',
    title: 'Onboarding',
    route: '/onboarding',
    group: 'Operations',
    tier: 'legacy',
    classification: 'legacy',
    visibility: 'hidden',
    platform: 'console',
    roles: ['Operator', 'Consultant', 'AssessmentEngineer'],
    aliases: ['setup wizard', 'getting started', 'onboard'],
    keywords: ['onboarding', 'setup', 'wizard', 'getting started', 'new tenant'],
    metadata: {
      mcimId: 'MCIM-18.6-ONBOARDING',
      capability: 'Tenant Onboarding Wizard',
      family: 'commercial-intake',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/onboarding/page.tsx',
      maturity: 'functional',
      lifecycle: 'legacy',
      businessValue:
        'Guided tenant setup flow — superseded by direct admin provisioning but retained for assisted onboarding scenarios.',
    },
  },

  {
    id: 'products',
    title: 'Products',
    route: '/products',
    group: 'Operations',
    tier: 'legacy',
    classification: 'legacy',
    visibility: 'hidden',
    platform: 'console',
    roles: ['Operator', 'Consultant', 'AssessmentEngineer'],
    aliases: ['product list', 'catalog'],
    keywords: ['products', 'catalog', 'legacy', 'list'],
    metadata: {
      mcimId: 'MCIM-18.6-PRODUCTS',
      capability: 'Legacy Product Catalog',
      family: 'commercial-intake',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/products/page.tsx',
      maturity: 'latent',
      lifecycle: 'legacy',
      businessValue:
        'Legacy product browsing surface — retained for backward compatibility while commercial intake migrates to the new provider model.',
    },
  },

  {
    id: 'product-detail',
    title: 'Product Detail',
    route: '/products/[productId]',
    group: 'Operations',
    tier: 'contextual',
    classification: 'contextual',
    visibility: 'hidden',
    platform: 'console',
    roles: ['Operator', 'Consultant', 'AssessmentEngineer'],
    aliases: ['product view', 'product page'],
    keywords: ['product', 'detail', 'view', 'legacy'],
    breadcrumbParent: 'products',
    metadata: {
      mcimId: 'MCIM-18.6-PRODUCT-DETAIL',
      capability: 'Legacy Product Detail',
      family: 'commercial-intake',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/products/[id]/page.tsx',
      maturity: 'latent',
      lifecycle: 'legacy',
      businessValue: 'Individual product record view within the legacy product catalog.',
    },
  },

  {
    id: 'product-new',
    title: 'New Product',
    route: '/products/new',
    group: 'Operations',
    tier: 'hidden',
    classification: 'hidden',
    visibility: 'hidden',
    platform: 'console',
    roles: ['Operator', 'Consultant', 'AssessmentEngineer'],
    aliases: ['create product', 'add product'],
    keywords: ['product', 'new', 'create', 'add', 'legacy'],
    metadata: {
      mcimId: 'MCIM-18.6-PRODUCT-NEW',
      capability: 'Legacy Product Creation',
      family: 'commercial-intake',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/products/new/page.tsx',
      maturity: 'latent',
      lifecycle: 'legacy',
      businessValue:
        'Legacy product creation form — hidden pending migration to structured provider catalogue.',
    },
  },

  {
    id: 'assessment-legacy',
    title: 'Assessments',
    route: '/assessment',
    group: 'Governance',
    tier: 'legacy',
    classification: 'legacy',
    visibility: 'hidden',
    platform: 'console',
    roles: ['Operator', 'Consultant', 'AssessmentEngineer'],
    aliases: ['assessment wizard', 'legacy assessment', 'snapshot assessment'],
    keywords: ['assessment', 'wizard', 'legacy', 'snapshot', 'questionnaire'],
    metadata: {
      mcimId: 'MCIM-18.6-ASSESS-LEGACY',
      capability: 'Legacy Assessment Wizard',
      family: 'delivery',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/assessment/page.tsx',
      maturity: 'functional',
      lifecycle: 'legacy',
      businessValue:
        'Original Tier-1 Snapshot assessment wizard — deprecated in favour of Field Assessments but retained for in-flight engagements.',
    },
  },

  {
    id: 'report-viewer',
    title: 'Report Viewer',
    route: '/reports/[reportId]',
    group: 'Trust',
    tier: 'contextual',
    classification: 'contextual',
    visibility: 'hidden',
    platform: 'console',
    roles: ['Operator', 'Consultant', 'AssessmentEngineer', 'CISO', 'Executive'],
    aliases: ['report', 'assessment report', 'advisory report'],
    keywords: ['report', 'pdf', 'advisory', 'assessment', 'output', 'findings'],
    breadcrumbParent: 'field-assessments',
    metadata: {
      mcimId: 'MCIM-18.6-REPORT-VIEW',
      capability: 'Assessment Report Viewer',
      family: 'delivery',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/reports/[reportId]/page.tsx',
      maturity: 'strong',
      lifecycle: 'stable',
      businessValue:
        'Renders the AI-generated advisory PDF report for a completed field assessment engagement.',
    },
  },

  // ─── PR 18.6.8 — Workspace Integration ───────────────────────────────────────

  {
    id: 'operations-workspace',
    title: 'Operations Workspace',
    route: '/workspace',
    group: 'Operations',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Operator', 'Administrator', 'CISO'],
    aliases: ['operations', 'ops workspace', 'work queue', 'case workspace'],
    keywords: ['operations', 'workspace', 'case', 'work queue', 'investigation', 'delegation'],
    metadata: {
      mcimId: 'MCIM-18.6-OPS-WS',
      capability: 'Enterprise Operations Workspace',
      family: 'operator-execution',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/workspace/page.tsx',
      maturity: 'functional',
      lifecycle: 'growing',
      businessValue:
        'Unified operator workspace for managing active cases, work queues, delegations, and cross-authority investigations.',
    },
  },

  {
    id: 'trust-center-workspace',
    title: 'Trust Center',
    route: '/trust-center',
    group: 'Trust',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'console',
    roles: ['Auditor', 'CISO', 'Executive'],
    aliases: ['trust', 'trust workspace', 'trust hub', 'verification center'],
    keywords: ['trust', 'verification', 'certificate', 'scorecard', 'benchmark', 'assurance'],
    metadata: {
      mcimId: 'MCIM-18.6-TRUST-CTR',
      capability: 'Enterprise Trust Center',
      family: 'trust-center',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/console/app/trust-center/page.tsx',
      maturity: 'functional',
      lifecycle: 'growing',
      businessValue:
        'Centralised trust hub providing scorecard, evidence graph, governance replay, change intelligence, and SLA forecasting for auditors and executives.',
    },
  },
];

for (const item of items) {
  CONSOLE_REGISTRY.register(item);
}
