import { NavigationRegistry } from '../registry';
import type { NavigationItem } from '../types';

export const PORTAL_REGISTRY = new NavigationRegistry();

const items: NavigationItem[] = [
  {
    id: 'portal-overview',
    title: 'Overview',
    route: '/',
    group: 'Portal',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'portal',
    roles: ['Customer', 'MSP', 'Auditor', 'Consultant'],
    aliases: ['home', 'dashboard', 'portal home', 'summary'],
    keywords: ['overview', 'home', 'summary', 'status', 'dashboard'],
    metadata: {
      mcimId: 'MCIM-18.6-PRT-OVERVIEW',
      capability: 'Portal Overview',
      family: 'closed-loop',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/portal/app/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Customer entry point — provides a consolidated status summary of active engagements, open findings, and remediation progress.',
    },
  },

  {
    id: 'portal-login',
    title: 'Login',
    route: '/login',
    group: 'Portal',
    tier: 'hidden',
    classification: 'hidden',
    visibility: 'hidden',
    platform: 'portal',
    roles: ['Customer', 'MSP', 'Auditor', 'Consultant'],
    aliases: ['sign in', 'auth', 'authenticate'],
    keywords: ['login', 'sign in', 'auth', 'authentication'],
    metadata: {
      mcimId: 'MCIM-18.6-PRT-LOGIN',
      capability: 'Portal Authentication',
      family: 'identity-grants',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/portal/app/login/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue: 'Secure authentication gate for all portal users.',
    },
  },

  {
    id: 'portal-accept-invite',
    title: 'Accept Invite',
    route: '/accept-invite',
    group: 'Portal',
    tier: 'hidden',
    classification: 'hidden',
    visibility: 'hidden',
    platform: 'portal',
    roles: ['Customer', 'MSP', 'Auditor', 'Consultant'],
    aliases: ['invite', 'invitation', 'accept', 'join'],
    keywords: ['invite', 'invitation', 'accept', 'join', 'onboard'],
    metadata: {
      mcimId: 'MCIM-18.6-PRT-INVITE',
      capability: 'Portal Invitation Acceptance',
      family: 'identity-grants',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/portal/app/accept-invite/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Handles token-based invitation links sent to new portal users — completes account activation and role assignment.',
    },
  },

  {
    id: 'portal-engagement',
    title: 'Assessment',
    route: '/engagement',
    group: 'Portal',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'portal',
    roles: ['Customer', 'MSP', 'Auditor', 'Consultant'],
    aliases: ['engagement', 'assessment', 'engagement list', 'my assessments'],
    keywords: ['engagement', 'assessment', 'questionnaire', 'survey', 'active'],
    metadata: {
      mcimId: 'MCIM-18.6-PRT-ENGAGE',
      capability: 'Portal Assessment Engagement',
      family: 'delivery',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/portal/app/engagement/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Customer-facing view of all active and past assessment engagements — entry point for completing questionnaires and tracking progress.',
    },
  },

  {
    id: 'portal-engagement-detail',
    title: 'Engagement Detail',
    route: '/engagement/[engagementId]',
    group: 'Portal',
    tier: 'contextual',
    classification: 'contextual',
    visibility: 'hidden',
    platform: 'portal',
    roles: ['Customer', 'MSP', 'Auditor', 'Consultant'],
    aliases: ['engagement view', 'assessment detail', 'single engagement'],
    keywords: ['engagement', 'assessment', 'detail', 'questionnaire', 'answer'],
    breadcrumbParent: 'portal-engagement',
    metadata: {
      mcimId: 'MCIM-18.6-PRT-ENGAGE-DTL',
      capability: 'Portal Engagement Detail',
      family: 'delivery',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/portal/app/engagement/[engagementId]/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Deep-dive into a single customer engagement — question-by-question response entry, status tracking, and assessor comments.',
    },
  },

  {
    id: 'portal-findings',
    title: 'Findings',
    route: '/findings',
    group: 'Portal',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'portal',
    roles: ['Customer', 'MSP', 'Auditor', 'Consultant'],
    aliases: ['issues', 'risks', 'gaps', 'findings list', 'open findings'],
    keywords: ['findings', 'issues', 'risks', 'gaps', 'vulnerabilities', 'recommendations'],
    metadata: {
      mcimId: 'MCIM-18.6-PRT-FINDINGS',
      capability: 'Portal Findings Review',
      family: 'closed-loop',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/portal/app/findings/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Displays all identified risk findings for the customer organisation — prioritised by severity and mapped to remediation actions.',
    },
  },

  {
    id: 'portal-reports',
    title: 'Reports',
    route: '/reports',
    group: 'Portal',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'portal',
    roles: ['Customer', 'MSP', 'Auditor', 'Consultant'],
    aliases: ['advisory reports', 'pdf reports', 'assessment reports', 'report list'],
    keywords: ['report', 'advisory', 'pdf', 'executive', 'summary', 'output', 'document'],
    metadata: {
      mcimId: 'MCIM-18.6-PRT-REPORTS',
      capability: 'Portal Report Library',
      family: 'delivery',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/portal/app/reports/page.tsx',
      maturity: 'strong',
      lifecycle: 'core',
      businessValue:
        'Library of AI-generated advisory reports from completed engagements — customers access, download, and share governance evidence.',
    },
  },

  {
    id: 'portal-coverage',
    title: 'Coverage',
    route: '/coverage',
    group: 'Portal',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'portal',
    roles: ['Customer', 'MSP', 'Auditor', 'Consultant'],
    aliases: ['control coverage', 'framework coverage', 'compliance coverage', 'coverage map'],
    keywords: ['coverage', 'control', 'framework', 'compliance', 'mapping', 'scope'],
    metadata: {
      mcimId: 'MCIM-18.6-PRT-COVERAGE',
      capability: 'Portal Compliance Coverage',
      family: 'continuous-posture',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/portal/app/coverage/page.tsx',
      maturity: 'functional',
      lifecycle: 'stable',
      businessValue:
        'Shows which compliance framework controls are covered, partially met, or missing — gives customers a clear picture of their regulatory posture.',
    },
  },

  {
    id: 'portal-attestation',
    title: 'Attestation',
    route: '/attestation',
    group: 'Portal',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'portal',
    roles: ['Customer', 'MSP', 'Auditor', 'Consultant'],
    aliases: ['sign-off', 'certify', 'attest', 'acknowledgement', 'sign off'],
    keywords: ['attestation', 'sign-off', 'certify', 'acknowledge', 'confirm', 'evidence'],
    metadata: {
      mcimId: 'MCIM-18.6-PRT-ATTEST',
      capability: 'Portal Attestation',
      family: 'trust-audit',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/portal/app/attestation/page.tsx',
      maturity: 'functional',
      lifecycle: 'stable',
      businessValue:
        'Collects formal customer attestations against control statements — creates signed, time-stamped evidence for auditors.',
    },
  },

  {
    id: 'portal-remediation',
    title: 'Remediation',
    route: '/remediation',
    group: 'Portal',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'portal',
    roles: ['Customer', 'MSP', 'Auditor', 'Consultant'],
    aliases: ['fixes', 'action items', 'remediation plan', 'remediate', 'action plan'],
    keywords: ['remediation', 'fix', 'action', 'plan', 'resolve', 'mitigation', 'task'],
    metadata: {
      mcimId: 'MCIM-18.6-PRT-REMEDIATE',
      capability: 'Portal Remediation Tracker',
      family: 'closed-loop',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/portal/app/remediation/page.tsx',
      maturity: 'functional',
      lifecycle: 'growing',
      businessValue:
        'Task board for tracking remediation of identified findings — closes the loop between discovery and resolution for audit purposes.',
    },
  },

  {
    id: 'portal-continuity',
    title: 'Continuity',
    route: '/continuity',
    group: 'Portal',
    tier: 'primary',
    classification: 'primary',
    visibility: 'visible',
    platform: 'portal',
    roles: ['Customer', 'MSP', 'Auditor', 'Consultant'],
    aliases: ['business continuity', 'bcp', 'dr', 'disaster recovery', 'continuity plan'],
    keywords: ['continuity', 'business continuity', 'dr', 'recovery', 'resilience', 'plan'],
    metadata: {
      mcimId: 'MCIM-18.6-PRT-CONTINUITY',
      capability: 'Portal Business Continuity',
      family: 'continuous-posture',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/portal/app/continuity/page.tsx',
      maturity: 'partial',
      lifecycle: 'growing',
      businessValue:
        'Surfaces AI-specific business continuity considerations and recovery posture to customers as part of their governance programme.',
    },
  },

  {
    id: 'portal-assistant',
    title: 'AI Assistant',
    route: '/assistant',
    group: 'Portal',
    tier: 'secondary',
    classification: 'secondary',
    visibility: 'visible',
    platform: 'portal',
    roles: ['Customer', 'MSP', 'Auditor', 'Consultant'],
    aliases: ['chat', 'ai chat', 'ask ai', 'portal chat', 'help assistant'],
    keywords: ['assistant', 'chat', 'ai', 'help', 'question', 'guidance', 'advisory'],
    metadata: {
      mcimId: 'MCIM-18.6-PRT-ASSISTANT',
      capability: 'Portal AI Assistant',
      family: 'knowledge',
      authority: 'FrostGate Platform',
      sourceOfTruth: 'apps/portal/app/assistant/page.tsx',
      maturity: 'functional',
      lifecycle: 'growing',
      businessValue:
        'AI-powered guidance assistant for portal users — answers governance questions and explains findings using the customer-scoped corpus.',
    },
  },
];

for (const item of items) {
  PORTAL_REGISTRY.register(item);
}
