from __future__ import annotations

from services.plane_registry.models import AuthClass, PlaneDef, RouteException

COMMON_GATES = ("check_plane_registry", "route-inventory-audit")
# /admin is intentionally control-only to avoid multi-plane ambiguity under longest-prefix matching.
ADMIN_PREFIX_POLICY = "control_only"


def ex(
    method: str,
    path: str,
    class_name: str,
    why: str,
    *,
    permanent: bool = True,
    expires_at: str = "",
) -> RouteException:
    return RouteException(
        method=method,
        path=path,
        class_name=class_name,
        justification=why,
        permanent=permanent,
        expires_at=expires_at,
    )


PLANE_REGISTRY: list[PlaneDef] = [
    PlaneDef(
        plane_id="control",
        route_prefixes=(
            "/control-plane",
            "/control/testing",
            "/control-tower",
            "/compliance",
            "/compliance-cp",
            "/enterprise-controls",
            "/exceptions",
            "/breakglass",
            "/governance",
            "/config",
            "/planes",
            "/health",
            "/status",
            "/internal",
            "/admin",
            "/_debug",
            "/_legacy",
            "/dev",
        ),
        allowed_dependency_categories=("auth", "tenant", "db", "rate", "breakglass"),
        required_make_targets=("control-plane-check", "plane-registry-spot"),
        required_ci_gates=COMMON_GATES,
        maturity_tag="production-grade",
        required_route_invariants=("auth", "scoped", "tenant_bound", "admin_prefix:control_only"),
        auth_class=AuthClass(
            required_scope_prefixes=("control-plane:", "governance:", "admin:", "compliance:", "audit:", "keys:", "dev:"),
            require_any_scope=True,
            tenant_binding_required=True,
        ),
        public_routes=(
            ex("GET", "/health", "public", "Unauthenticated health probe."),
            ex("GET", "/health/live", "public", "Kubernetes liveness probe."),
            ex("GET", "/health/ready", "public", "Kubernetes readiness probe."),
            ex("GET", "/health/detailed", "public", "Detailed health probe endpoint."),
            ex("GET", "/status", "public", "Legacy status endpoint."),
            ex("GET", "/v1/status", "public", "Legacy v1 status endpoint."),
        ),
        global_routes=(
            ex("GET", "/admin/system/health", "global_admin", "Global operator health view."),
            ex("GET", "/admin/keys/needing-rotation", "global_admin", "Global operator key rotation report."),
            ex("GET", "/admin/keys/{key_prefix}/rotation-status", "global_admin", "Global operator key rotation state."),
            ex("POST", "/admin/keys/{key_prefix}/rotate", "global_admin", "Global operator key rotate action."),
            ex("GET", "/admin/usage/all", "global_admin", "Global usage summary."),
            
            ex("GET", "/control-plane/v2/delegation", "global_admin", "Delegation listing is global governance metadata."),
            ex("POST", "/control-plane/v2/delegation", "global_admin", "Delegation create is global governance metadata."),
            ex("DELETE", "/control-plane/v2/delegation/{delegation_id}", "global_admin", "Delegation revoke is global governance metadata."),
            ex("GET", "/control-plane/v2/terminal/allowlist", "global_admin", "Allowlist is global governance metadata."),
            ex("GET", "/_debug/routes", "bootstrap", "Debug route catalog; blocked in prod-like mode."),
            ex("GET", "/_legacy/ui_feed/_disabled", "bootstrap", "Legacy disabled route; blocked in prod-like mode."),
        ),
    ),
    PlaneDef(
        plane_id="security",
        route_prefixes=("/auth", "/keys"),
        allowed_dependency_categories=("auth", "tenant", "db", "rate", "breakglass"),
        required_make_targets=("security-regression-gates",),
        required_ci_gates=COMMON_GATES,
        maturity_tag="production-grade",
        required_route_invariants=("auth", "tenant_bound"),
        auth_class=AuthClass(required_scope_prefixes=("admin:", "keys:"), require_any_scope=True, tenant_binding_required=True),
    ),
    PlaneDef(
        plane_id="data",
        route_prefixes=("/ingest", "/feed", "/decisions", "/defend", "/stats", "/billing"),
        allowed_dependency_categories=("auth", "tenant", "db", "rate"),
        required_make_targets=("soc-invariants",),
        required_ci_gates=COMMON_GATES,
        maturity_tag="production-grade",
        required_route_invariants=("auth", "tenant_bound"),
        auth_class=AuthClass(required_scope_prefixes=("ingest:", "feed:", "decisions:", "defend:", "stats:", "admin:"), require_any_scope=True, tenant_binding_required=True),
        global_routes=(
            ex("GET", "/stats/debug", "bootstrap", "Debug stats endpoint is operational bootstrap path."),
        ),
    ),
    PlaneDef(
        plane_id="agent",
        route_prefixes=("/agent",),
        allowed_dependency_categories=("auth", "tenant", "db", "rate"),
        required_make_targets=("agent-unit",),
        required_ci_gates=COMMON_GATES,
        maturity_tag="tester-ready",
        required_route_invariants=("auth", "tenant_bound"),
        auth_class=AuthClass(require_any_scope=False, tenant_binding_required=True, allow_unscoped_keys=False),
        auth_exempt_routes=(
            ex("POST", "/agent/enroll", "auth_exempt", "Bootstrap enrollment before scoped key issuance."),
            ex("POST", "/agent/cert/enroll", "auth_exempt", "Bootstrap cert enrollment before scoped key issuance."),
        ),
        global_routes=(
            ex("POST", "/agent/cert/renew", "bootstrap", "Device cert flow binds identity, not tenant."),
            ex("GET", "/agent/cert/status", "bootstrap", "Cert status is device-level bootstrap metadata."),
            ex("POST", "/agent/commands/ack", "bootstrap", "Ack uses device identity channel."),
            ex("POST", "/agent/commands/poll", "bootstrap", "Poll uses device identity channel."),
            ex("POST", "/agent/heartbeat", "bootstrap", "Heartbeat is device channel metadata."),
            ex("POST", "/agent/key/rotate", "bootstrap", "Key rotate uses device channel metadata."),
            ex("POST", "/agent/log/anchor", "bootstrap", "Anchor log uses device channel metadata."),
            ex("GET", "/agent/policy/fetch", "bootstrap", "Policy fetch uses device channel metadata."),
            ex("GET", "/agent/update/manifest", "bootstrap", "Update manifest lookup is device channel metadata."),
            ex("POST", "/agent/update/manifest", "bootstrap", "Update manifest ack is device channel metadata."),
            ex("POST", "/agent/update/report", "bootstrap", "Update report uses device channel metadata."),
        ),
    ),
    PlaneDef(
        plane_id="ai",
        route_prefixes=("/ai", "/ai-plane"),
        allowed_dependency_categories=("auth", "tenant", "db", "rate"),
        required_make_targets=("ai-plane-spot",),
        required_ci_gates=COMMON_GATES,
        maturity_tag="tester-ready",
        required_route_invariants=("auth", "tenant_bound", "scoped"),
        auth_class=AuthClass(required_scope_prefixes=("compliance:", "ai:", "admin:"), require_any_scope=True, tenant_binding_required=True),
    ),
    PlaneDef(
        plane_id="connector",
        route_prefixes=("/modules", "/missions", "/rings", "/roe", "/v1"),
        allowed_dependency_categories=("auth", "tenant", "db", "rate"),
        required_make_targets=("check-connectors-rls",),
        required_ci_gates=COMMON_GATES,
        maturity_tag="experimental",
        required_route_invariants=("auth", "tenant_bound"),
        auth_class=AuthClass(required_scope_prefixes=("attestation:",), require_any_scope=False, tenant_binding_required=True, allow_unscoped_keys=True),
        public_routes=(
            ex("GET", "/v1/status", "public", "Legacy connector status endpoint."),
            ex("GET", "/missions", "public", "Mission catalog is public in current design."),
            ex("GET", "/missions/{mission_id}", "public", "Mission metadata endpoint is public in current design."),
            ex("GET", "/missions/{mission_id}/status", "public", "Mission status endpoint is public in current design."),
            ex("GET", "/rings/isolation", "public", "Ring isolation matrix is public in current design."),
            ex("GET", "/rings/policies", "public", "Ring policies are public in current design."),
            ex("POST", "/rings/route", "public", "Ring router is public in current design."),
            ex("POST", "/roe/evaluate", "public", "ROE evaluate is public in current design."),
            ex("GET", "/roe/policy", "public", "ROE policy is public in current design."),
        ),
        global_routes=(
            ex("GET", "/modules", "global_admin", "Global module index."),
            ex("GET", "/modules/{module_id}", "global_admin", "Global module metadata."),
            ex("GET", "/modules/enforce/{module_id}", "global_admin", "Global module enforcement preview."),
            ex("POST", "/modules/register", "global_admin", "Global module registration."),
        ),
    ),
    PlaneDef(
        plane_id="evidence",
        route_prefixes=("/audit", "/evidence", "/approvals", "/attestation", "/forensics"),
        allowed_dependency_categories=("auth", "tenant", "db", "rate"),
        required_make_targets=("audit-chain-verify",),
        required_ci_gates=COMMON_GATES,
        maturity_tag="production-grade",
        required_route_invariants=("auth", "tenant_bound", "scoped"),
        auth_class=AuthClass(required_scope_prefixes=("audit:", "attestation:", "forensics:", "admin:", "compliance:"), require_any_scope=True, tenant_binding_required=True),
        global_routes=(
            ex("POST", "/approvals", "global_admin", "Approval creation operates at platform governance scope."),
            ex("POST", "/approvals/verify", "global_admin", "Approval verification operates at platform governance scope."),
            ex("GET", "/approvals/{subject_type}/{subject_id}", "global_admin", "Approval lookup operates at platform governance scope."),
            ex("POST", "/evidence/bundles", "global_admin", "Evidence bundles can be globally exported."),
            ex("GET", "/evidence/bundles/{bundle_id}", "global_admin", "Evidence bundle retrieval can be global."),
            ex("POST", "/evidence/verify", "global_admin", "Evidence verification can be global."),
        ),
    ),
    PlaneDef(
        plane_id="ui",
        route_prefixes=("/ui",),
        allowed_dependency_categories=("auth", "tenant", "rate"),
        required_make_targets=("test-quality-gate",),
        required_ci_gates=COMMON_GATES,
        maturity_tag="production-grade",
        required_route_invariants=("auth", "tenant_bound"),
        auth_class=AuthClass(required_scope_prefixes=("ui:", "admin:", "audit:", "controls:", "forensics:"), require_any_scope=True, tenant_binding_required=True),
        bootstrap_routes=(
            ex("GET", "/ui/csrf", "bootstrap", "CSRF bootstrap endpoint before tenant-bound session materializes."),
            ex("GET", "/ui/scopes", "bootstrap", "Scope introspection endpoint before tenant-bound flow."),
            ex("GET", "/ui/token", "bootstrap", "Token bootstrap endpoint before tenant-bound flow."),
        ),
        global_routes=(
            ex("GET", "/ui/ai", "global_admin", "Global AI dashboard overview."),
            ex("GET", "/ui/controls", "global_admin", "Global controls dashboard overview."),
            ex("GET", "/ui/controls/{inv_id}", "global_admin", "Global control detail view."),
            ex("GET", "/ui/dash/controls", "global_admin", "Global controls dashboard rollup."),
            ex("GET", "/ui/dash/forensics", "global_admin", "Global forensics dashboard rollup."),
            ex("GET", "/ui/dash/posture", "global_admin", "Global posture dashboard rollup."),
            ex("GET", "/ui/feed", "global_admin", "Global UI feed endpoint."),
            ex("POST", "/ui/audit/packet", "global_admin", "Global audit packet creation."),
            ex("GET", "/ui/audit/packet/{packet_id}/download", "global_admin", "Global audit packet download."),
        ),
    ),
]


def list_planes() -> list[dict[str, object]]:
    return [p.to_dict() for p in PLANE_REGISTRY]
