"""SQLAlchemy ORM models for Trust Arc persistence tables.

Mirrors migrations 0108 (trust intelligence + decision memory) and
0109 (auditor proof + certification). Tables are append-only; no UPDATE
or DELETE operations are issued by the service layer.

Classes (P0-6A):
  FaTrustIntelligenceSnapshot  — fa_trust_intelligence_snapshots (0108)
  FaAuditorProofPackage        — fa_auditor_proof_packages (0109)
  FaTrustCertification         — fa_trust_certifications (0109)
  FaTrustDecisionMemory        — fa_trust_decision_memory (0108)

Classes (P0-7 — previously table-only, no ORM):
  FaTrustIntelligenceLedger      — fa_trust_intelligence_ledger (0108)
  FaDecisionReconstructionRecord — fa_decision_reconstruction_records (0109)
  FaChainOfCustodyRecord         — fa_chain_of_custody_records (0109)
"""

from __future__ import annotations

from sqlalchemy import Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from api.db_models import Base


class FaTrustIntelligenceSnapshot(Base):
    """Immutable, cryptographically signed trust intelligence state capture.

    Generated by services.field_assessment.trust_intelligence_authority
    .generate_trust_intelligence_snapshot(). Indexed by tenant + engagement
    + created_at for latest-snapshot queries.
    """

    __tablename__ = "fa_trust_intelligence_snapshots"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    tenant_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    engagement_id: Mapped[str] = mapped_column(String(64), nullable=False)
    authority_version: Mapped[str] = mapped_column(String(128), nullable=False)
    posture_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    posture_level: Mapped[str] = mapped_column(
        String(64), nullable=False, default="unknown"
    )
    trend_direction: Mapped[str] = mapped_column(
        String(64), nullable=False, default="stable"
    )
    trend_velocity: Mapped[str] = mapped_column(
        String(64), nullable=False, default="none"
    )
    risk_level: Mapped[str] = mapped_column(
        String(64), nullable=False, default="unknown"
    )
    risk_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    priorities_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    insights_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    recommendations_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0
    )
    forecast_projected_score: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0
    )
    graph_node_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    payload_hashes: Mapped[str] = mapped_column(Text, nullable=False)  # JSON
    posture_result: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    trend_result: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    risk_result: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    priorities: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    insights: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    recommendations: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    forecast_result: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    graph_result: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    snapshot_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    snapshot_signature: Mapped[str] = mapped_column(Text, nullable=False)
    signing_key_id: Mapped[str] = mapped_column(String(64), nullable=False)
    created_at: Mapped[str] = mapped_column(String(64), nullable=False)
    schema_version: Mapped[str] = mapped_column(
        String(16), nullable=False, default="1.0"
    )


class FaAuditorProofPackage(Base):
    """Complete, cryptographically signed auditor proof bundle.

    Generated by services.field_assessment.auditor_proof_authority
    .generate_auditor_proof_package(). 8 sections: evidence, replay,
    graph, confidence, intelligence, ledger, decisions, historical.
    """

    __tablename__ = "fa_auditor_proof_packages"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    tenant_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    engagement_id: Mapped[str] = mapped_column(String(64), nullable=False)
    authority_version: Mapped[str] = mapped_column(String(128), nullable=False)
    assessed_by: Mapped[str] = mapped_column(
        String(128), nullable=False, default="human"
    )
    section_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    section_hashes: Mapped[str] = mapped_column(Text, nullable=False)  # JSON
    sections: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    package_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    package_signature: Mapped[str] = mapped_column(Text, nullable=False)
    signing_key_id: Mapped[str] = mapped_column(String(64), nullable=False)
    verified_at: Mapped[str] = mapped_column(String(64), nullable=False)
    schema_version: Mapped[str] = mapped_column(
        String(16), nullable=False, default="1.0"
    )


class FaTrustCertification(Base):
    """Deterministic, evidence-backed trust certification.

    Generated by services.field_assessment.auditor_proof_authority
    .generate_trust_certification(). Composite = 0.70×trust + 0.30×confidence.
    Five levels: bronze/silver/gold/platinum/enterprise. 90-day validity.
    """

    __tablename__ = "fa_trust_certifications"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    tenant_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    engagement_id: Mapped[str] = mapped_column(String(64), nullable=False)
    certification_level: Mapped[str] = mapped_column(
        String(64), nullable=False, default="not_certified"
    )
    trust_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    confidence_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    composite_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    scored_by: Mapped[str] = mapped_column(
        String(128), nullable=False, default="deterministic_composite_v1"
    )
    valid_from: Mapped[str] = mapped_column(String(64), nullable=False)
    valid_until: Mapped[str] = mapped_column(String(64), nullable=False)
    verification_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    authority_version: Mapped[str] = mapped_column(String(128), nullable=False)
    schema_version: Mapped[str] = mapped_column(
        String(16), nullable=False, default="1.0"
    )


class FaTrustDecisionMemory(Base):
    """Governance decision audit record.

    Generated by services.field_assessment.trust_intelligence_authority
    .generate_decision_memory(). entity_type is extensible: human, agent,
    autonomous_system, agi, or any future governed entity type.
    """

    __tablename__ = "fa_trust_decision_memory"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    tenant_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    engagement_id: Mapped[str] = mapped_column(String(64), nullable=False)
    decision_type: Mapped[str] = mapped_column(String(64), nullable=False)
    entity_type: Mapped[str] = mapped_column(
        String(64), nullable=False, default="human"
    )
    decision_reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    supporting_intelligence: Mapped[str | None] = mapped_column(
        Text, nullable=True
    )  # JSON
    supporting_evidence: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    authority_version: Mapped[str] = mapped_column(String(128), nullable=False)
    created_at: Mapped[str] = mapped_column(String(64), nullable=False)
    schema_version: Mapped[str] = mapped_column(
        String(16), nullable=False, default="1.0"
    )


# ---------------------------------------------------------------------------
# P0-7: ORM models for tables that existed in migrations 0108/0109
# but had no SQLAlchemy class.
# ---------------------------------------------------------------------------


class FaTrustIntelligenceLedger(Base):
    """Hash-chained tamper-evident ledger of trust intelligence snapshots.

    Migration 0108. Append-only. Each entry chains to the previous via
    previous_hash (genesis sentinel: '0' * 64). Enables ledger integrity
    verification without replaying all snapshots.
    """

    __tablename__ = "fa_trust_intelligence_ledger"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    tenant_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    engagement_id: Mapped[str] = mapped_column(String(64), nullable=False)
    snapshot_id: Mapped[str] = mapped_column(String(64), nullable=False)
    snapshot_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    snapshot_signature: Mapped[str] = mapped_column(Text, nullable=False)
    signing_key_id: Mapped[str] = mapped_column(Text, nullable=False)
    authority_version: Mapped[str] = mapped_column(String(128), nullable=False)
    posture_level: Mapped[str] = mapped_column(
        String(32), nullable=False, default="unknown"
    )
    risk_level: Mapped[str] = mapped_column(
        String(32), nullable=False, default="unknown"
    )
    posture_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    previous_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    ledger_entry_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    timestamp: Mapped[str] = mapped_column(String(64), nullable=False)
    created_at: Mapped[str] = mapped_column(String(64), nullable=False)
    schema_version: Mapped[str] = mapped_column(
        String(16), nullable=False, default="1.0"
    )


class FaDecisionReconstructionRecord(Base):
    """Legal defense decision reconstruction record.

    Migration 0109. Append-only. Captures the full question-and-answer
    reconstruction of a governance decision for legal/audit review.
    """

    __tablename__ = "fa_decision_reconstruction_records"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    tenant_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    engagement_id: Mapped[str] = mapped_column(String(64), nullable=False)
    reconstruction_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    total_decisions: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    snapshot_hash: Mapped[str] = mapped_column(String(64), nullable=False, default="")
    replay_valid: Mapped[bool] = mapped_column(nullable=False, default=False)
    questions_answered: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    decision_reconstruction: Mapped[str | None] = mapped_column(
        Text, nullable=True
    )  # JSON
    evidence_chain: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    intelligence_chain: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    replay_validation: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    authority_version: Mapped[str] = mapped_column(String(128), nullable=False)
    generated_at: Mapped[str] = mapped_column(String(64), nullable=False)
    schema_version: Mapped[str] = mapped_column(
        String(16), nullable=False, default="1.0"
    )


class FaChainOfCustodyRecord(Base):
    """Hash-linked chain of custody event record.

    Migration 0109. Append-only. Tracks lifecycle events (evidence_created,
    evidence_reviewed, evidence_approved, report_generated, report_exported,
    trust_verified, package_generated) in a tamper-evident chain.

    entity_type is extensible: human | reviewer | approver | agent |
    agent_fleet | autonomous_workflow | autonomous_system | agi.
    """

    __tablename__ = "fa_chain_of_custody_records"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    tenant_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    engagement_id: Mapped[str] = mapped_column(String(64), nullable=False)
    sequence: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    event_type: Mapped[str] = mapped_column(String(64), nullable=False)
    entity_type: Mapped[str] = mapped_column(
        String(64), nullable=False, default="human"
    )
    entity_id: Mapped[str] = mapped_column(String(255), nullable=False, default="")
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    timestamp: Mapped[str] = mapped_column(String(64), nullable=False)
    previous_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    custody_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    custody_metadata: Mapped[str | None] = mapped_column(
        "metadata", Text, nullable=True
    )  # JSON
    authority_version: Mapped[str] = mapped_column(String(128), nullable=False)
    schema_version: Mapped[str] = mapped_column(
        String(16), nullable=False, default="1.0"
    )
